// Phase 7 自 app.js 迁入；唯一机械转换：模块级可变状态（state/page/filter/searchTerm/
// reportPeriod/storageProblem/APP_ENTRY/DEFAULT_PAGE/modal 等）→ ctx.*，函数体逐字保留。

import { allowedPermission, ctx, date, esc } from '../context.js';
import { total } from '../../sales.js';
import { money } from '../../shared/money.js';
import { reportGiftDetails, reportGiftPerson, reportMoney, reportNotes, reportOtherDetails, reportPaymentMethods, reportSaleDetails, reportViewModel } from '../../reporting.js';

function reportPage() {
  if (!allowedPermission('report.view')) return '<p>当前身份没有报表权限，请切换管理员或由管理员分配“查看经营报表”权限。</p>';
  const { rows, totals, roomTotals, roomSales, roomOther, retailOrders, categoryRows, sellerRows } = reportViewModel(ctx.state, ctx.reportPeriod);
  const roomBody=rows.length?rows.map(({room,order,sales,other})=>{
    const gifts=reportGiftDetails(order), saleDetails=reportSaleDetails(order), otherDetails=reportOtherDetails(order), notes=reportNotes(order, ctx.reportPeriod);
    return `<tr class="has-order"><th scope="row"><strong>${esc(room.id)}</strong><small>${esc(room.type)}</small></th><td class="money-cell">${reportMoney(order.base)}</td><td class="money-cell">${reportMoney(order.gift)}</td><td class="money-cell emphasis">${reportMoney(sales)}</td><td class="money-cell">${reportMoney(other)}</td><td>${esc(reportPaymentMethods(order)||'—')}</td><td class="detail-cell">${gifts.length?gifts.map(esc).join('<br>'):'—'}</td><td>${esc(reportGiftPerson(order)||'—')}</td><td class="detail-cell">${saleDetails.length?saleDetails.map(esc).join('<br>'):'—'}</td><td class="detail-cell">${otherDetails.length?otherDetails.map(esc).join('<br>'):'—'}</td><td class="money-cell">${reportMoney(order.rounding)}</td><td class="money-cell total-cell">${reportMoney(total(order))}</td><td class="note-cell">${notes.length?notes.map(esc).join('<br>'):'—'}</td></tr>`;
  }).join(''):'<tr class="empty-period"><td colspan="13">本统计周期暂无开房记录</td></tr>';
  const retailBody=retailOrders.length?retailOrders.map(order=>`<tr><th scope="row">${esc(order.id)}</th><td>${date(order.createdAt||order.time)}</td><td class="detail-cell">${reportSaleDetails(order).map(esc).join('<br>')}</td><td>${esc([...new Set((order.sales||[]).map(line=>line.person||'归属未记录'))].join('、'))}</td><td>${esc(reportPaymentMethods(order)||'—')}</td><td class="money-cell total-cell">${reportMoney(total(order))}</td></tr>`).join(''):'<tr class="empty-period"><td colspan="6">本统计周期暂无独立零售交易</td></tr>';
  const breakdown=rows=>rows.length?rows.map(([label,amount])=>`<div class="bill-line"><span>${esc(label)}</span><b>${reportMoney(amount)}</b></div>`).join(''):'<p class="muted">暂无商品销售。</p>';
  const periodLabel = ctx.reportPeriod==='day'?'日报':ctx.reportPeriod==='week'?'周报':'月报';
  return `<p class="eyebrow">经营数据</p><div class="report-heading"><div><h1>营业${periodLabel}</h1><p class="muted">${ctx.reportPeriod==='day'?'按当天':ctx.reportPeriod==='week'?'按本周':'按本月'}演示记录汇总 · ${date(ctx.state.clock)} · 金额单位：元</p></div><label class="report-period">统计范围<select id="report-period"><option value="day" ${ctx.reportPeriod==='day'?'selected':''}>日报</option><option value="week" ${ctx.reportPeriod==='week'?'selected':''}>周报</option><option value="month" ${ctx.reportPeriod==='month'?'selected':''}>月报</option></select></label></div><section class="summary report-summary"><div><strong>${rows.length}</strong><span>有消费房间</span></div><div><strong>${retailOrders.length}</strong><span>独立零售交易</span></div><div><strong>${reportMoney(totals.total)}</strong><span>全部账单合计</span></div></section><div class="report-total-strip"><span>商品销售及套餐赠饮 <b>${reportMoney(totals.sales)}</b></span><span>后续赠酒参考值 <b>${reportMoney(totals.gift)}</b></span><span>免零金额 <b>${reportMoney(totals.rounding)}</b></span></div><div class="report-table-wrap"><table class="report-table"><caption><strong>房间消费明细</strong><span>左右滑动查看完整报表</span></caption><thead><tr><th scope="col">房号</th><th scope="col">房费</th><th scope="col">套餐赠饮</th><th scope="col">商品销售</th><th scope="col">其他消费</th><th scope="col">买单方式</th><th scope="col">后续赠酒</th><th scope="col">赠送人</th><th scope="col">商品销售明细</th><th scope="col">其他明细</th><th scope="col">免零</th><th scope="col">合计</th><th scope="col">备注</th></tr></thead><tbody>${roomBody}</tbody><tfoot><tr><th scope="row">房间合计</th><td>${reportMoney(roomTotals.base)}</td><td>${reportMoney(roomTotals.sales-roomSales)}</td><td>${reportMoney(roomSales)}</td><td>${reportMoney(roomOther)}</td><td>—</td><td>—</td><td>—</td><td>—</td><td>—</td><td>${reportMoney(roomTotals.rounding)}</td><td>${reportMoney(roomTotals.total)}</td><td>—</td></tr></tfoot></table></div><div class="report-table-wrap"><table class="report-table retail-report-table"><caption><strong>独立零售明细</strong><span>无需房间，成交后立即结清</span></caption><thead><tr><th scope="col">零售单号</th><th scope="col">成交时间</th><th scope="col">商品明细</th><th scope="col">销售归属</th><th scope="col">付款方式</th><th scope="col">合计</th></tr></thead><tbody>${retailBody}</tbody></table></div><section class="report-breakdowns"><div class="panel"><h2>商品分类销售</h2>${breakdown(categoryRows)}</div><div class="panel"><h2>销售人员归属</h2>${breakdown(sellerRows)}</div></section><p class="muted report-note">商品销售按订单中的成交价、名称和分类快照汇总；零售与房间订单都计入账单合计。统计周期沿用现有订单日期口径，正式营业日与班次留待后续设计。</p>`;
}

export {
  reportPage
};
