import http from 'node:http';
import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
const files = { '/': ['index.html', 'text/html'], '/index.html': ['index.html', 'text/html'], '/admin': ['admin.html', 'text/html'], '/admin.html': ['admin.html', 'text/html'], '/app.js': ['app.js', 'text/javascript'], '/rules.js': ['rules.js', 'text/javascript'], '/catalog.js': ['catalog.js', 'text/javascript'], '/packages.js': ['packages.js', 'text/javascript'], '/inventory.js': ['inventory.js', 'text/javascript'], '/sales.js': ['sales.js', 'text/javascript'], '/rooms.js': ['rooms.js', 'text/javascript'], '/deposits.js': ['deposits.js', 'text/javascript'], '/expenses.js': ['expenses.js', 'text/javascript'], '/procurement.js': ['procurement.js', 'text/javascript'], '/incidents.js': ['incidents.js', 'text/javascript'], '/handover.js': ['handover.js', 'text/javascript'], '/reviewInbox.js': ['reviewInbox.js', 'text/javascript'], '/reporting.js': ['reporting.js', 'text/javascript'], '/ui/context.js': ['ui/context.js', 'text/javascript'], '/ui/shell.js': ['ui/shell.js', 'text/javascript'], '/ui/forms.js': ['ui/forms.js', 'text/javascript'], '/ui/pages/rooms.js': ['ui/pages/rooms.js', 'text/javascript'], '/ui/pages/retail.js': ['ui/pages/retail.js', 'text/javascript'], '/ui/pages/deposits.js': ['ui/pages/deposits.js', 'text/javascript'], '/ui/pages/tasks.js': ['ui/pages/tasks.js', 'text/javascript'], '/ui/pages/admin.js': ['ui/pages/admin.js', 'text/javascript'], '/ui/pages/expenses.js': ['ui/pages/expenses.js', 'text/javascript'], '/ui/pages/procurement.js': ['ui/pages/procurement.js', 'text/javascript'], '/ui/pages/incidents.js': ['ui/pages/incidents.js', 'text/javascript'], '/ui/pages/reports.js': ['ui/pages/reports.js', 'text/javascript'], '/ui/pages/mine.js': ['ui/pages/mine.js', 'text/javascript'], '/ui/dialogs/rooms.js': ['ui/dialogs/rooms.js', 'text/javascript'], '/ui/dialogs/orders.js': ['ui/dialogs/orders.js', 'text/javascript'], '/ui/dialogs/retail.js': ['ui/dialogs/retail.js', 'text/javascript'], '/ui/dialogs/deposits.js': ['ui/dialogs/deposits.js', 'text/javascript'], '/ui/dialogs/operations.js': ['ui/dialogs/operations.js', 'text/javascript'], '/ui/dialogs/admin.js': ['ui/dialogs/admin.js', 'text/javascript'], '/migrations.js': ['migrations.js', 'text/javascript'], '/persistence.js': ['persistence.js', 'text/javascript'], '/shared/money.js': ['shared/money.js', 'text/javascript'], '/shared/time.js': ['shared/time.js', 'text/javascript'], '/shared/identity.js': ['shared/identity.js', 'text/javascript'], '/theme.js': ['theme.js', 'text/javascript'], '/style.css': ['style.css', 'text/css'] };
const port = Number(process.env.PORT || 4173);
http.createServer(async (req, res) => {
  const file = files[new URL(req.url, 'http://localhost').pathname];
  if (!file) { res.writeHead(404); res.end('Not found'); return; }
  try {
    const body = await readFile(fileURLToPath(new URL(file[0], import.meta.url)));
    res.writeHead(200, { 'Content-Type': `${file[1]}; charset=utf-8`, 'Cache-Control': 'no-store', 'X-Content-Type-Options': 'nosniff' });
    res.end(body);
  } catch { res.writeHead(500); res.end('Unable to load demo'); }
}).listen(port, '0.0.0.0', () => console.log(`KTV demo: http://localhost:${port}`));
